#!/bin/sh

args=$@

case "`uname`" in
  MINGW*)
    exec_name=graboo-windown-x64.exe;;
  Darwin*)
    # detect if we were double-clicked
    [ "$HOME" = "$PWD" ] && [ "$#" -eq 0 ] && {
      echo "Detected MAC OSX launched script...."
      echo "Swapping to UI"
      args="ide"
    }

    case "`uname -m`" in
      x86_64)
        exec_name=graboo-macos-x64;;
      arm64)
        exec_name=graboo-macos-arm64;;
      *)
        echo "Architecture not supported"
        exit 1
        ;;
    esac
    ;;
  Linux*)
    # detect if we were double-clicked in Linux
    [ "$(readlink -f /proc/$(ps -o ppid:1= -p $$)/exe)" != "$(readlink -f "$SHELL")" ] && [ "$#" -eq 0 ] && {
      args="ide"
    }

    exec_name=graboo-linux-x64;;
  *)
    echo "Platform not supported"
    exit 1
    ;;
esac

mkdir -p $HOME/.graboo

executable=$HOME/.graboo/$exec_name

if [ -e "$executable-new" ] ; then
  mv $executable-new $executable
fi

if [ ! -e "$executable" ] ; then
  url="https://github.com/jamesward/graboo/releases/latest/download/$exec_name"
  if command -v wget > /dev/null; then
    wget --quiet "$url" -O $executable
  elif command -v curl > /dev/null; then
    curl -q -L -f -o "$executable" "$url"
  else
    echo "Could not download $url"
  fi

  chmod +x $executable
fi

exec "$executable" $args
