on: push

jobs:
  check-env:
    outputs:
      gcp-credentials-defined: ${{ steps.get-gcp-credentials.outputs.defined }}
    runs-on: ubuntu-latest
    steps:
      - id: get-gcp-credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        if: ${{ env.GCP_CREDENTIALS != '' }}
        run: |
          echo "::set-output name=defined::true"

  build:
    name: build-and-deploy
    needs: [ check-env ]
    if: needs.check-env.outputs.gcp-credentials-defined == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # todo: run on PR or move to test ?
      - name: Create Container
        run: |
          ./gradlew :server:jib --image=gcr.io/${{ steps.auth.outputs.project_id }}/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Deploy Service
        uses: jamesward/easycloudrun/deploy@main
        env:
          PROJECT_ID: ${{ steps.auth.outputs.project_id }}
          COMMIT_SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ github.event.repository.name }}
          IMAGE_VERSION: ${{ github.sha }}
          REGION: us-central1