on: push

jobs:
  build:
    name: build-and-deploy
    if: ${{ secrets.GCP_CREDENTIALS != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # todo: run on PR or move to test ?
      - name: Create Container
        run: |
          ./gradlew :server:jib --image=gcr.io/${{ steps.auth.outputs.project_id }}/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Deploy Service
        uses: jamesward/easycloudrun/deploy@main
        env:
          PROJECT_ID: ${{ steps.auth.outputs.project_id }}
          COMMIT_SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ github.event.repository.name }}
          IMAGE_VERSION: ${{ github.sha }}
          REGION: us-central1