on:
  push:
    tags:
      - "v*"

concurrency: ci-${{ github.ref }}

jobs:
#  test:
#    uses: ./.github/workflows/test.yaml

  publish-plugin:
    if: false
#    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - id: secret-check
        name: Check for Secret Availability
        run: |
          if [ "${{ secrets.GRADLE_PUBLISH_KEY }}" != '' ] && [ "${{ secrets.GRADLE_PUBLISH_SECRET }}" != '' ]; then
            echo "available=true" >> $GITHUB_OUTPUT;
          else
            echo "available=false" >> $GITHUB_OUTPUT;
          fi

      - name: Checkout
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gradle
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: gradle/gradle-build-action@v2

      - name: Publish
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        run: |
          ./gradlew :gradle-plugin:publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}

      - id: get-version
        name: Get Version
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        run: |
          echo "version=$(./gradlew :version -q)" >> $GITHUB_OUTPUT

      - name: Update Versions
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        run: |
          sed -ie "s/version \"[^\"]*\"/version \"${{ steps.get-version.outputs.version }}\"/" examples/*/*/settings.gradle.kts

      - name: Commit Version Updates
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            examples/*/*/settings.gradle.kts
          commit-msg: Update version
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-executables:
#    needs: [test]
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
        include:
          - os: ubuntu
            runs: ubuntu-latest
            platform-name: linuxX64
            release-file: bootstrapper.kexe
            asset-name: graboo-linux-x64
          - os: macos
            runs: macos-latest
            platform-name: macosArm64
            release-file: bootstrapper.kexe
            asset-name: graboo-macos-arm64
          - os: windows
            runs: windows-latest
            platform-name: mingwX64
            release-file: bootstrapper.exe
            asset-name: graboo-windows-x64.exe
    runs-on: ${{ matrix.runs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: graboo executable
        run: |
          ./gradlew :bootstrapper:linkReleaseExecutable
          ls bootstrapper/build/bin
          ls bootstrapper/build/bin/${{ matrix.platform-name }}/releaseExecutable

      - name: run upx
        uses: svenstaro/upx-action@v2
        with:
          files: bootstrapper/build/bin/${{ matrix.platform-name }}/releaseExecutable/${{ matrix.release-file }}
          args: --best --lzma

      - name: upload executables
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset-name }}
          path: bootstrapper/build/bin/${{ matrix.platform-name }}/releaseExecutable/${{ matrix.release-file }}

      - name: release binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bootstrapper/build/bin/${{ matrix.platform-name }}/releaseExecutable/${{ matrix.release-file }}
          asset_name: ${{ matrix.asset-name }}
          overwrite: true
          tag: ${{ github.ref }}

      - name: update graboo
        run: |
          for f in examples/*/*; do cp -p bootstrapper/scripts/* $f; done

      - name: test graboo on ubuntu & mac
        if: matrix.os != 'windows'
        run: |
          cd examples/javaapp/hello-world
          ./graboo run
          # todo: verify output

      - name: test graboo
        if: matrix.os == 'windows'
        run: |
          cd examples/javaapp/hello-world
          graboo run
          # todo: verify output

      - name: Commit graboo Updates
        if: matrix.os == 'ubuntu'
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            examples/*/*/graboo
          commit-msg: Update graboo
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit graboo.cmd Updates
        if: matrix.os == 'windows'
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            examples/*/*/graboo.cmd
          commit-msg: Update graboo.cmd
          github-token: ${{ secrets.GITHUB_TOKEN }}