on:
  workflow_call:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**' # tags are tested by publish action

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]
        include:
          - os: ubuntu
            runs: ubuntu-latest
          - os: macos
            runs: macos-latest
          - os: windows
            runs: windows-latest

    runs-on: ${{ matrix.runs }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - uses: SimonMarquis/android-accept-licenses@v1

      - name: Test ${{ matrix.os }}
        if: matrix.os != 'windows'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew test
          ./gradlew allTests

      # on windows these are separate so that test failures cause a job failure

      - name: Test ${{ matrix.os }}
        if: matrix.os == 'windows'
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .\gradlew test

      - name: allTest ${{ matrix.os }}
        if: matrix.os == 'windows'
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .\gradlew allTests